### ISSUE TITLE
64 bit build

### ISSUE THREAD

**Issue by cgand** [fadookie/jumpcut#2]
Request for a 64bit build as 32bit app will be no more supported on next mac OS release.
Thanks to keep this useful utility update.

**Comment by fadookie** [comment]
Sorry, the official jumpcut repo is https://github.com/snark/jumpcut - I made this fork before I knew it existed on github using git-svn, so it doesn't show up as a fork. Although I wouldn't hold out hope for any feature requests getting addressed, there hasn't been a commit in almost 6 years.
