### ISSUE TITLE
Feature request: Ignore any sensitive data you copy from password manager

### ISSUE THREAD

**Issue by bunk3m** [fadookie/jumpcut#3]
Hi. Looks like this is where Jumpcut is being worked on so here is a feature request.

Jumpcut should ignore any sensitive data you copy from apps such as 1Password, KeePassX/XC or Keychain Access. 

This should be doable for all applications that mark their data as "transient".  

In the case that this hasn't be implemented for an application, there should be a blacklist preference/functionality so you can make sure that any apps you add to the blacklist won’t add your copied sensitive data to Jumpcut.

**Comment by fadookie** [comment]
Sorry, the official jumpcut repo is https://github.com/snark/jumpcut - I made this fork before I knew it existed on github using svn-git, so it doesn't show up as a fork. Although I wouldn't hold out hope for any feature requests getting addressed, there hasn't been a commit in almost 6 years.

I'm not sure if jumpcut even has an awareness of the source its data is coming from, it's using some pretty old carbon code.
